spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.olma: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics