apiVersion: 1

contactPoints:
  - orgId: 1
    name: OLma Discord Alerts
    receivers:
      - uid: olma_discord_alerts
        type: discord
        settings:
          url: $DISCORD_WEBHOOK_URL
          message: '{{ template "olma.discord.message" . }}'
          use_discord_username: false
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: OLma Discord Alerts
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    routes:
      - receiver: OLma Discord Alerts
        object_matchers:
          - - service
            - "="
            - olma-backend

templates:
  - orgId: 1
    name: olma.discord.message
    template: |
      {{ define "olma.discord.message" }}
      {{ range .Alerts }}
      [{{ .Status }}] {{ .Labels.alertname }}
      severity={{ .Labels.severity }}
      summary={{ .Annotations.summary }}
      description={{ .Annotations.description }}
      {{ end }}
      {{ end }}
